In [11]:
import pandas as pd
from sqlalchemy import create_engine
import pymysql
pymysql.install_as_MySQLdb()
from sqlalchemy import event, create_engine

In [12]:
ny_crime = "NYC_crime.csv"
nycrime_df = pd.read_csv(ny_crime)
nycrime_df.head()

,CMPLNT_NUM,CMPLNT_FR_DT,CMPLNT_FR_TM,CMPLNT_TO_DT,CMPLNT_TO_TM,RPT_DT,KY_CD,OFNS_DESC,PD_CD,PD_DESC,...,ADDR_PCT_CD,LOC_OF_OCCUR_DESC,PREM_TYP_DESC,PARKS_NM,HADEVELOPT,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lat_Lon
0,807539955,01/01/2016,12:00:00,01/24/2018,17:00:00,01/24/2018,361,OFF. AGNST PUB ORD SENSBLTY &,639,AGGRAVATED HARASSMENT 2,...,18,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,"988,085","217,902",40.764774,-73.986157,"(40.764774473000045, -73.986157253)"
1,908438691,01/01/2016,10:00:00,02/11/2018,16:00:00,02/11/2018,578,HARRASSMENT 2,638,"HARASSMENT,SUBD 3,4,5",...,24,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,"993,373","229,301",40.796058,-73.967052,"(40.79605784000006, -73.96705230699997)"
2,713483285,01/01/2016,00:00:00,02/15/2018,19:30:00,02/16/2018,112,THEFT-FRAUD,739,"FRAUD,UNCLASSIFIED-FELONY",...,32,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,"1,001,374","238,163",40.820370,-73.938133,"(40.82036969600006, -73.93813284599996)"
3,178447094,01/01/2016,08:00:00,03/18/2017,17:00:00,02/21/2018,109,GRAND LARCENY,420,"LARCENY,GRAND BY OPEN/COMPROMISE CELL PHONE ACCT",...,34,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,"1,001,606","251,324",40.856492,-73.937261,"(40.85649236300002, -73.93726057999999)"
4,911003056,01/01/2016,12:00:00,02/16/2018,12:00:00,02/28/2018,109,GRAND LARCENY,407,"LARCENY,GRAND BY DISHONEST EMP",...,20,INSIDE,OTHER,NaN,NaN,"989,731","222,727",40.778017,-73.980211,"(40.77801697500007, -73.98021132399998)"

In [13]:
list(nycrime_df)

['CMPLNT_NUM',
 'CMPLNT_FR_DT',
 'CMPLNT_FR_TM',
 'CMPLNT_TO_DT',
 'CMPLNT_TO_TM',
 'RPT_DT',
 'KY_CD',
 'OFNS_DESC',
 'PD_CD',
 'PD_DESC',
 'CRM_ATPT_CPTD_CD',
 'LAW_CAT_CD',
 'JURIS_DESC',
 'BORO_NM',
 'ADDR_PCT_CD',
 'LOC_OF_OCCUR_DESC',
 'PREM_TYP_DESC',
 'PARKS_NM',
 'HADEVELOPT',
 'X_COORD_CD',
 'Y_COORD_CD',
 'Latitude',
 'Longitude',
 'Lat_Lon']

In [14]:
# Create a filtered dataframe from specific columns
crime_cols = [ "RPT_DT", "OFNS_DESC","Latitude", "Longitude"]
crime_trans= nycrime_df[crime_cols].copy()
crime_trans.head()

       RPT_DT                      OFNS_DESC   Latitude  Longitude
0  01/24/2018  OFF. AGNST PUB ORD SENSBLTY &  40.764774 -73.986157
1  02/11/2018                  HARRASSMENT 2  40.796058 -73.967052
2  02/16/2018                    THEFT-FRAUD  40.820370 -73.938133
3  02/21/2018                  GRAND LARCENY  40.856492 -73.937261
4  02/28/2018                  GRAND LARCENY  40.778017 -73.980211

In [15]:
# Clean-up Date 
dates = []
dates = crime_trans['RPT_DT'].values
dates [1]

'02/11/2018'

In [19]:
# Get the Year
YYYY = []
for d in dates:
    d=str(d)
    YYYY.append(d[6:10])

In [20]:
# Get the Month
MM = []
for d in dates:
    MM.append(d[0:2])
print(MM)

['01', '02', '02', '02', '02', '03', '10', '10', '11', '12', '12', '01', '07', '05', '10', '01', '09', '03', '01', '01', '01', '07', '03', '04', '02', '02', '08', '06', '06', '02', '01', '01', '04', '02', '08', '09', '05', '03', '09', '10', '10', '03', '04', '05', '12', '10', '04', '03', '04', '04', '03', '04', '04', '11', '04', '04', '02', '02', '06', '06', '10', '10', '04', '01', '02', '03', '04', '10', '10', '01', '01', '12', '12', '06', '01', '01', '03', '03', '07', '07', '09', '05', '08', '01', '11', '01', '02', '06', '01', '01', '01', '01', '02', '01', '01', '01', '01', '01', '01', '06', '01', '06', '08', '06', '06', '08', '08', '01', '02', '03', '07', '03', '07', '10', '09', '05', '08', '08', '08', '02', '01', '02', '04', '08', '08', '08', '04', '01', '03', '08', '01', '08', '07', '08', '08', '01', '02', '03', '04', '05', '05', '05', '09', '12', '01', '03', '03', '05', '11', '12', '12', '03', '07', '05', '02', '02', '09', '08', '04', '04', '09', '01', '03', '04', '10', '12', '09', '02', '06', '10', '03', '11', '08', '12', '02', '05', '02', '01', '10', '01', '03', '03', '08', '12', '11', '05', '01', '05', '02', '05', '01', '01', '01', '02', '06', '09', '10', '11', '01', '04', '02', '03', '03', '03', '05', '11', '12', '01', '05', '08', '02', '12', '12', '04', '10', '03', '03', '09', '09', '03', '03', '10', '01', '04', '12', '05', '10']

In [21]:
#Get the Day
DD = []
for d in dates:
    DD.append(d[3:5])
print(DD)

['24', '11', '16', '21', '28', '05', '09', '14', '12', '18', '19', '11', '02', '17', '16', '18', '01', '30', '28', '29', '30', '18', '22', '17', '16', '10', '27', '14', '14', '28', '31', '21', '04', '01', '06', '21', '23', '16', '29', '02', '01', '23', '26', '29', '25', '22', '09', '02', '06', '16', '20', '14', '14', '03', '17', '03', '13', '06', '25', '27', '11', '23', '20', '30', '09', '01', '03', '15', '18', '21', '27', '03', '06', '21', '10', '29', '22', '27', '02', '11', '18', '14', '11', '19', '11', '19', '06', '06', '19', '19', '19', '19', '21', '19', '19', '19', '19', '19', '19', '07', '29', '23', '04', '26', '26', '03', '16', '02', '09', '17', '24', '07', '06', '11', '27', '02', '10', '07', '27', '20', '29', '21', '04', '05', '06', '08', '28', '08', '13', '16', '31', '21', '11', '28', '29', '28', '12', '21', '11', '03', '22', '31', '08', '26', '15', '06', '22', '17', '06', '19', '04', '26', '03', '03', '01', '16', '26', '08', '02', '13', '19', '11', '27', '17', '16', '10', '07', '21', '02', '16', '04', '29', '14', '01', '21', '14', '12', '23', '24', '10', '09', '20', '16', '13', '12', '10', '18', '13', '21', '10', '05', '28', '23', '02', '13', '20', '17', '28', '03', '12', '05', '04', '16', '19', '08', '13', '09', '30', '03', '01', '23', '18', '18', '18', '03', '16', '20', '20', '22', '29', '11', '09', '11', '12', '21', '04', '08']

In [22]:
crime_trans["Month"]=MM
crime_trans["Day"]=DD
crime_trans["Year"]=YYYY

In [61]:
final_crime = crime_trans[["Date","Year","Month", "Day", "OFNS_DESC","Latitude", "Longitude"]]

In [62]:
final_crime["Date"] = final_crime["Month"] + "-" + final_crime["Day"]
final_crime.head()

C:\Users\zhiyi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

    Date  Year Month Day                      OFNS_DESC   Latitude  Longitude
0  01-24  2018    01  24  OFF. AGNST PUB ORD SENSBLTY &  40.764774 -73.986157
1  02-11  2018    02  11                  HARRASSMENT 2  40.796058 -73.967052
2  02-16  2018    02  16                    THEFT-FRAUD  40.820370 -73.938133
3  02-21  2018    02  21                  GRAND LARCENY  40.856492 -73.937261
4  02-28  2018    02  28                  GRAND LARCENY  40.778017 -73.980211

In [63]:
final_crime = final_crime.rename(index=str, columns={ 'OFNS_DESC':'Offense Description'})
final_crime.head()

    Date  Year Month Day            Offense Description   Latitude  Longitude
0  01-24  2018    01  24  OFF. AGNST PUB ORD SENSBLTY &  40.764774 -73.986157
1  02-11  2018    02  11                  HARRASSMENT 2  40.796058 -73.967052
2  02-16  2018    02  16                    THEFT-FRAUD  40.820370 -73.938133
3  02-21  2018    02  21                  GRAND LARCENY  40.856492 -73.937261
4  02-28  2018    02  28                  GRAND LARCENY  40.778017 -73.980211

In [65]:
#Create Database
connection_string = "root:19060Dst;@localhost/"
engine = create_engine(f'mysql://{connection_string}')

connection = engine.connect()

In [66]:
connection.execute('use etl_db;')

In [67]:
db_connection_string = "root:19060Dst;@localhost/etl_db"
db_engine = create_engine(f'mysql://{db_connection_string}')

# Confirm tables
db_engine.table_names()

['nyc_crime', 'nyc_crime_concat', 'nyc_parking']

In [68]:
final_crime.head()

    Date  Year Month Day            Offense Description   Latitude  Longitude
0  01-24  2018    01  24  OFF. AGNST PUB ORD SENSBLTY &  40.764774 -73.986157
1  02-11  2018    02  11                  HARRASSMENT 2  40.796058 -73.967052
2  02-16  2018    02  16                    THEFT-FRAUD  40.820370 -73.938133
3  02-21  2018    02  21                  GRAND LARCENY  40.856492 -73.937261
4  02-28  2018    02  28                  GRAND LARCENY  40.778017 -73.980211

In [69]:
final_crime.to_sql(name='nyc_crime', con=db_engine, if_exists='replace', index = False)

In [70]:
results = db_engine.execute('select * from nyc_crime')

In [71]:
for item in results:
    print(item)

('01-24', '2018', '01', '24', 'OFF. AGNST PUB ORD SENSBLTY &', 40.764774473, -73.986157253)
('02-11', '2018', '02', '11', 'HARRASSMENT 2', 40.7960578400001, -73.967052307)
('02-16', '2018', '02', '16', 'THEFT-FRAUD', 40.8203696960001, -73.938132846)
('02-21', '2018', '02', '21', 'GRAND LARCENY', 40.856492363, -73.93726058)
('02-28', '2018', '02', '28', 'GRAND LARCENY', 40.7780169750001, -73.980211324)
('03-05', '2018', '03', '05', 'SEX CRIMES', 40.8399082010001, -73.936083587)
('10-09', '2018', '10', '09', 'SEX CRIMES', 40.815732053, -73.945420411)
('10-14', '2018', '10', '14', 'THEFT-FRAUD', 40.7067067770001, -74.010933704)
('11-12', '2018', '11', '12', 'SEX CRIMES', 40.8087499040001, -73.9525858059999)
('12-18', '2018', '12', '18', 'THEFT-FRAUD', 40.7242001540001, -73.9772256429999)
('12-19', '2018', '12', '19', 'VEHICLE AND TRAFFIC LAWS', 40.731667658, -73.9894150869999)
('01-11', '2018', '01', '11', 'GRAND LARCENY', 40.8648942040001, -73.92407815)
('07-02', '2018', '07', '02', 'GRAND LARCENY', 40.829802455, -73.941806221)
('05-17', '2018', '05', '17', 'GRAND LARCENY', 40.7435116090001, -73.994227355)
('10-16', '2018', '10', '16', 'GRAND LARCENY', 40.739843856, -73.985523708)
('01-18', '2018', '01', '18', 'PETIT LARCENY', 40.8095968380001, -73.9497855979999)
('09-01', '2018', '09', '01', 'ASSAULT 3 & RELATED OFFENSES', 40.8540274060001, -73.927528234)
('03-30', '2018', '03', '30', 'OFF. AGNST PUB ORD SENSBLTY &', 40.730756883, -74.000769976)
('01-28', '2018', '01', '28', 'HARRASSMENT 2', 40.7741636750001, -73.952910098)
('01-29', '2018', '01', '29', 'ADMINISTRATIVE CODE', 40.801911169, -73.955393569)
('01-30', '2018', '01', '30', 'OFF. AGNST PUB ORD SENSBLTY &', 40.7602200740001, -73.9801985619999)
('07-18', '2018', '07', '18', 'RAPE', 40.814850289, -73.956681848)
('03-22', '2018', '03', '22', 'RAPE', 40.815732053, -73.945420411)
('04-17', '2018', '04', '17', 'THEFT-FRAUD', 40.8040460070001, -73.936620103)
('02-16', '2018', '02', '16', 'ASSAULT 3 & RELATED OFFENSES', 40.7141423670001, -73.989338511)
('02-10', '2018', '02', '10', 'PETIT LARCENY', 40.861266748, -73.925669364)
('08-27', '2018', '08', '27', 'GRAND LARCENY', 40.7439680090001, -73.977911783)
('06-14', '2018', '06', '14', 'THEFT-FRAUD', 40.8664185690001, -73.9215564209999)
('06-14', '2018', '06', '14', 'GRAND LARCENY', 40.8664185690001, -73.9215564209999)
('02-28', '2018', '02', '28', 'GRAND LARCENY', 40.8375595150001, -73.9375169529999)
('01-31', '2018', '01', '31', 'OFF. AGNST PUB ORD SENSBLTY &', 40.767794199, -73.991387694)
('01-21', '2018', '01', '21', 'OFF. AGNST PUB ORD SENSBLTY &', 40.8267322610001, -73.9501014809999)
('04-04', '2018', '04', '04', 'GRAND LARCENY', 40.7329087850001, -73.97490979)
('02-01', '2018', '02', '01', 'PETIT LARCENY', 40.709564416, -74.0064362809999)
('08-06', '2018', '08', '06', 'GRAND LARCENY', 40.756978196, -73.9783406129999)
('09-21', '2018', '09', '21', 'HARRASSMENT 2', 40.749681321, -73.9879577409999)
('05-23', '2018', '05', '23', 'HARRASSMENT 2', 40.759991331, -73.9648032549999)
('03-16', '2018', '03', '16', 'HARRASSMENT 2', 40.84770738, -73.9387797109999)
('09-29', '2018', '09', '29', 'SEX CRIMES', 40.800694331, -73.941109286)
('10-02', '2018', '10', '02', 'NYS LAWS-UNCLASSIFIED FELONY', 40.716344152, -74.001253193)
('10-01', '2018', '10', '01', 'RAPE', 40.8399082010001, -73.936083587)
('03-23', '2018', '03', '23', 'HARRASSMENT 2', 40.768652643, -73.953914012)
('04-26', '2018', '04', '26', 'GRAND LARCENY', 40.776412362, -73.948250846)
('05-29', '2018', '05', '29', 'RAPE', 40.8514877740001, -73.9354579669999)
('12-25', '2018', '12', '25', 'GRAND LARCENY', 40.781451127, -73.9832939819999)
('10-22', '2018', '10', '22', 'RAPE', 40.73669807, -73.983316026)
('04-09', '2018', '04', '09', 'HARRASSMENT 2', 40.7897884650001, -73.944517181)
('03-02', '2018', '03', '02', 'GRAND LARCENY', 40.770861863, -73.9828381309999)
('04-06', '2018', '04', '06', 'NYS LAWS-UNCLASSIFIED FELONY', 40.716344152, -74.001253193)
('04-16', '2018', '04', '16', 'PETIT LARCENY', 40.7685239040001, -73.9871384369999)
('03-20', '2018', '03', '20', 'FRAUDS', 40.775230406, -73.976684667)
('04-14', '2018', '04', '14', 'FRAUDS', 40.778773711, -73.97595045)
('04-14', '2018', '04', '14', 'CRIMINAL MISCHIEF & RELATED OF', 40.796341237, -73.9411998159999)
('11-03', '2018', '11', '03', 'THEFT-FRAUD', 40.7673241, -73.984297521)
('04-17', '2018', '04', '17', 'GRAND LARCENY', 40.763865814, -73.984962561)
('04-03', '2018', '04', '03', 'GRAND LARCENY', 40.74242932, -73.984808613)
('02-13', '2018', '02', '13', 'THEFT-FRAUD', 40.8126320150001, -73.9630161039999)
('02-06', '2018', '02', '06', 'RAPE', 40.726554019, -73.987828427)
('06-25', '2018', '06', '25', 'UNAUTHORIZED USE OF A VEHICLE', 40.816601773, -73.9446718539999)
('06-27', '2018', '06', '27', 'NYS LAWS-UNCLASSIFIED FELONY', 40.85192304, -73.933447777)
('10-11', '2018', '10', '11', 'GRAND LARCENY', 40.719379863, -74.0002323269999)
('10-23', '2018', '10', '23', 'SEX CRIMES', 40.726554019, -73.987828427)
('04-20', '2018', '04', '20', 'THEFT-FRAUD', 40.750897813, -73.99626231)
('01-30', '2018', '01', '30', 'THEFT-FRAUD', 40.7316734280001, -73.993109848)
('02-09', '2018', '02', '09', 'THEFT-FRAUD', 40.821380135, -73.957103936)
('03-01', '2018', '03', '01', 'RAPE', 40.814850289, -73.956681848)
('04-03', '2018', '04', '03', 'OFF. AGNST PUB ORD SENSBLTY &', 40.7303726160001, -73.999110247)
('10-15', '2018', '10', '15', 'SEX CRIMES', 40.73669807, -73.983316026)
('10-18', '2018', '10', '18', 'GRAND LARCENY', 40.8230558820001, -73.9473943949999)
('01-21', '2018', '01', '21', 'THEFT-FRAUD', 40.800656132, -73.970257405)
('01-27', '2018', '01', '27', 'HARRASSMENT 2', 40.8396923810001, -73.9432648639999)
('12-03', '2018', '12', '03', 'THEFT-FRAUD', 40.7685239040001, -73.9871384369999)
('12-06', '2018', '12', '06', 'GRAND LARCENY', 40.710093847, -74.01060963)
('06-21', '2018', '06', '21', 'FRAUDS', 40.7960578400001, -73.967052307)
('01-10', '2018', '01', '10', 'RAPE', 40.8514877740001, -73.9354579669999)
('01-29', '2018', '01', '29', 'RAPE', 40.814850289, -73.956681848)
('03-22', '2018', '03', '22', 'GRAND LARCENY', 40.774077348, -73.964813863)
('03-27', '2018', '03', '27', 'GRAND LARCENY', 40.757588785, -73.9865918939999)
('07-02', '2018', '07', '02', 'RAPE', 40.800694331, -73.941109286)
('07-11', '2018', '07', '11', 'OFF. AGNST PUB ORD SENSBLTY &', 40.7308445780001, -74.005658984)
('09-18', '2018', '09', '18', 'SEX CRIMES', 40.814850289, -73.956681848)
('05-14', '2018', '05', '14', 'GRAND LARCENY', 40.7638737230001, -73.96042599)
('08-11', '2018', '08', '11', 'RAPE', 40.789260224, -73.947710001)
('01-19', '2018', '01', '19', 'FORGERY', 40.7587750440001, -73.9923851189999)
('11-11', '2018', '11', '11', 'HARRASSMENT 2', 40.7629635920001, -73.9935145279999)
('01-19', '2018', '01', '19', 'FORGERY', 40.779163, -73.9558348739999)
('02-06', '2018', '02', '06', 'FORGERY', 40.716344152, -74.001253193)
('06-06', '2018', '06', '06', 'PETIT LARCENY', 40.817290208, -73.956315366)
('01-19', '2018', '01', '19', 'FORGERY', 40.779163, -73.9558348739999)
('01-19', '2018', '01', '19', 'FORGERY', 40.751978863, -73.9899135479999)
('01-19', '2018', '01', '19', 'FORGERY', 40.780045767, -73.982915201)
('01-19', '2018', '01', '19', 'FORGERY', 40.775135338, -73.982291841)
('02-21', '2018', '02', '21', 'FRAUDS', 40.803221643, -73.967272709)
('01-19', '2018', '01', '19', 'FORGERY', 40.7550692300001, -73.9876716219999)
('01-19', '2018', '01', '19', 'FORGERY', 40.780045767, -73.982915201)
('01-19', '2018', '01', '19', 'FORGERY', 40.803915987, -73.9670231329999)
('01-19', '2018', '01', '19', 'FORGERY', 40.780045767, -73.982915201)
('01-19', '2018', '01', '19', 'FORGERY', 40.779163, -73.9558348739999)
('01-19', '2018', '01', '19', 'FORGERY', 40.779163, -73.9558348739999)
('06-07', '2018', '06', '07', 'HARRASSMENT 2', 40.7634656970001, -73.990828721)
('01-29', '2018', '01', '29', 'HARRASSMENT 2', 40.7740602470001, -73.9627992329999)
('06-23', '2018', '06', '23', 'ASSAULT 3 & RELATED OFFENSES', 40.756928384, -73.976275976)
('08-04', '2018', '08', '04', 'OFF. AGNST PUB ORD SENSBLTY &', 40.7308445780001, -74.005658984)
('06-26', '2018', '06', '26', 'HARRASSMENT 2', 40.817417796, -73.9527313679999)
('06-26', '2018', '06', '26', 'PETIT LARCENY', 40.743766388, -73.987973246)
('08-03', '2018', '08', '03', 'GRAND LARCENY', 40.756978196, -73.9783406129999)
('08-16', '2018', '08', '16', 'MISCELLANEOUS PENAL LAW', 40.8495048980001, -73.9287584969999)
('01-02', '2018', '01', '02', 'HARRASSMENT 2', 40.7761146390001, -73.9454528809999)
('02-09', '2018', '02', '09', 'OFF. AGNST PUB ORD SENSBLTY &', 40.7379890180001, -73.973540251)
('03-17', '2018', '03', '17', 'GRAND LARCENY', 40.854761099, -73.933510004)
('07-24', '2018', '07', '24', 'RAPE', 40.76717676, -73.963806683)
('03-07', '2018', '03', '07', 'GRAND LARCENY', 40.8129506380001, -73.9558810939999)
('07-06', '2018', '07', '06', 'FRAUDS', 40.794604263, -73.9478141499999)
('10-11', '2018', '10', '11', 'GRAND LARCENY', 40.7086669490001, -74.005033101)
('09-27', '2018', '09', '27', 'RAPE', 40.764818269, -73.9851897729999)
('05-02', '2018', '05', '02', 'GRAND LARCENY', 40.776704532, -73.951059671)
('08-10', '2018', '08', '10', 'RAPE', 40.783478055, -73.9647583409999)
('08-07', '2018', '08', '07', 'GRAND LARCENY', 40.8657226810001, -73.923440887)
('08-27', '2018', '08', '27', 'PETIT LARCENY', 40.826401859, -73.936793928)
('02-20', '2018', '02', '20', 'CRIMINAL MISCHIEF & RELATED OF', 40.7948167600001, -73.944408254)
('01-29', '2018', '01', '29', 'PETIT LARCENY', 40.7394834200001, -73.9797356079999)
('02-21', '2018', '02', '21', 'HARRASSMENT 2', 40.7861233140001, -73.9426135639999)
('04-04', '2018', '04', '04', 'GRAND LARCENY', 40.7442158000001, -73.982336146)
('08-05', '2018', '08', '05', 'PETIT LARCENY', 40.794515091, -73.966323533)
('08-06', '2018', '08', '06', 'OFF. AGNST PUB ORD SENSBLTY &', 40.761271557, -73.9688888379999)
('08-08', '2018', '08', '08', 'GRAND LARCENY', 40.763070772, -73.996687591)
('04-28', '2018', '04', '28', 'FRAUDS', 40.7960578400001, -73.967052307)
('01-08', '2018', '01', '08', 'OFF. AGNST PUB ORD SENSBLTY &', 40.7078207530001, -74.014540763)
('03-13', '2018', '03', '13', 'GRAND LARCENY', 40.781224949, -73.957570326)
('08-16', '2018', '08', '16', 'PETIT LARCENY', 40.7582323710001, -73.977430585)
('01-31', '2018', '01', '31', 'OFF. AGNST PUB ORD SENSBLTY &', 40.850948187, -73.9280701709999)
('08-21', '2018', '08', '21', 'OFF. AGNST PUB ORD SENSBLTY &', 40.7562662070001, -73.990501248)
('07-11', '2018', '07', '11', 'SEX CRIMES', 40.8087499040001, -73.9525858059999)
('08-28', '2018', '08', '28', 'ASSAULT 3 & RELATED OFFENSES', 40.8209643010001, -73.941477939)
('08-29', '2018', '08', '29', 'SEX CRIMES', 40.815732053, -73.945420411)
('01-28', '2018', '01', '28', 'GRAND LARCENY', 40.808497274, -73.9353985079999)
('02-12', '2018', '02', '12', 'OFF. AGNST PUB ORD SENSBLTY &', 40.706978808, -74.007121329)
('03-21', '2018', '03', '21', 'THEFT-FRAUD', 40.75063599, -73.970110103)
('04-11', '2018', '04', '11', 'SEX CRIMES', 40.734226128, -74.005406689)
('05-03', '2018', '05', '03', 'GRAND LARCENY', 40.7673487270001, -73.9608968489999)
('05-22', '2018', '05', '22', 'THEFT-FRAUD', 40.7494396700001, -73.9869255739999)
('05-31', '2018', '05', '31', 'SEX CRIMES', 40.76717676, -73.963806683)
('09-08', '2018', '09', '08', 'RAPE', 40.726554019, -73.987828427)
('12-26', '2018', '12', '26', 'HARRASSMENT 2', 40.781198238, -73.959617696)
('01-15', '2018', '01', '15', 'GRAND LARCENY', 40.8497762170001, -73.9375271649999)
('03-06', '2018', '03', '06', 'NYS LAWS-UNCLASSIFIED FELONY', 40.716344152, -74.001253193)
('03-22', '2018', '03', '22', 'CRIMINAL MISCHIEF & RELATED OF', 40.713143696, -74.004059506)
('05-17', '2018', '05', '17', 'SEX CRIMES', 40.753938938, -73.994843655)
('11-06', '2018', '11', '06', 'GRAND LARCENY', 40.757346324, -73.9801813679999)
('12-19', '2018', '12', '19', 'NYS LAWS-UNCLASSIFIED FELONY', 40.7878745990001, -73.928181646)
('12-04', '2018', '12', '04', 'BURGLARY', 40.757843983, -73.961797604)
('03-26', '2018', '03', '26', 'HARRASSMENT 2', 40.7388342510001, -73.9898614099999)
('07-03', '2018', '07', '03', 'RAPE', 40.800694331, -73.941109286)
('05-03', '2018', '05', '03', 'GRAND LARCENY', 40.8678578290001, -73.919085298)
('02-01', '2018', '02', '01', 'HARRASSMENT 2', 40.793464597, -73.968949638)
('02-16', '2018', '02', '16', 'ASSAULT 3 & RELATED OFFENSES', 40.727570158, -73.996126514)
('09-26', '2018', '09', '26', 'HARRASSMENT 2', 40.811169851, -73.9504491069999)
('08-08', '2018', '08', '08', 'PETIT LARCENY', 40.743598299, -73.982783803)
('04-02', '2018', '04', '02', 'THEFT-FRAUD', 40.7581440540001, -73.964598483)
('04-13', '2018', '04', '13', 'HARRASSMENT 2', 40.7739147440001, -73.988780154)
('09-19', '2018', '09', '19', 'HARRASSMENT 2', 40.816800597, -73.947240377)
('01-11', '2018', '01', '11', 'RAPE', 40.8087499040001, -73.9525858059999)
('03-27', '2018', '03', '27', 'SEX CRIMES', 40.8087499040001, -73.9525858059999)
('04-17', '2018', '04', '17', 'THEFT-FRAUD', 40.8040460070001, -73.936620103)
('10-16', '2018', '10', '16', 'PETIT LARCENY', 40.7445854950001, -73.9774857319999)
('12-10', '2018', '12', '10', 'GRAND LARCENY', 40.814890345, -73.961262699)
('09-07', '2018', '09', '07', 'HARRASSMENT 2', 40.749780113, -73.987780874)
('02-21', '2018', '02', '21', 'GRAND LARCENY', 40.7930754010001, -73.9710878229999)
('06-02', '2018', '06', '02', 'HARRASSMENT 2', 40.821256099, -73.9557166129999)
('10-16', '2018', '10', '16', 'GRAND LARCENY', 40.7482979910001, -73.988178144)
('03-04', '2018', '03', '04', 'FRAUDS', 40.7165145550001, -73.975893551)
('11-29', '2018', '11', '29', 'SEX CRIMES', 40.789260224, -73.947710001)
('08-14', '2018', '08', '14', 'GRAND LARCENY', 40.756978196, -73.9783406129999)
('12-01', '2018', '12', '01', 'PETIT LARCENY', 40.791783071, -73.972890486)
('02-21', '2018', '02', '21', 'GRAND LARCENY', 40.8557584810001, -73.930638777)
('05-14', '2018', '05', '14', 'GRAND LARCENY', 40.750411107, -73.985236286)
('02-12', '2018', '02', '12', 'NYS LAWS-UNCLASSIFIED FELONY', 40.716344152, -74.001253193)
('01-23', '2018', '01', '23', 'GRAND LARCENY', 40.7614047600001, -73.999676569)
('10-24', '2018', '10', '24', 'OFF. AGNST PUB ORD SENSBLTY &', 40.8619483680001, -73.927136388)
('01-10', '2018', '01', '10', 'NYS LAWS-UNCLASSIFIED FELONY', 40.716344152, -74.001253193)
('03-09', '2018', '03', '09', 'THEFT-FRAUD', 40.7534640760001, -73.994399743)
('03-20', '2018', '03', '20', 'GRAND LARCENY', 40.863003221, -73.924253843)
('08-16', '2018', '08', '16', 'RAPE', 40.76717676, -73.963806683)
('12-13', '2018', '12', '13', 'HARRASSMENT 2', 40.746934278, -73.993588267)
('11-12', '2018', '11', '12', 'HARRASSMENT 2', 40.790295342, -73.942682195)
('05-10', '2018', '05', '10', 'RAPE', 40.734226128, -74.005406689)
('01-18', '2018', '01', '18', 'GRAND LARCENY', 40.756352479, -73.9787956139999)
('05-13', '2018', '05', '13', 'SEX CRIMES', 40.764818269, -73.9851897729999)
('02-21', '2018', '02', '21', 'THEFT-FRAUD', 40.736833222, -73.988750312)
('05-10', '2018', '05', '10', 'HARRASSMENT 2', 40.7218220190001, -73.9874793509999)
('01-05', '2018', '01', '05', 'ASSAULT 3 & RELATED OFFENSES', 40.748592752, -73.9770909869999)
('01-28', '2018', '01', '28', 'GRAND LARCENY', 40.757346324, -73.9801813679999)
('01-23', '2018', '01', '23', 'ASSAULT 3 & RELATED OFFENSES', 40.811130194, -73.936714506)
('02-02', '2018', '02', '02', 'GRAND LARCENY', 40.780739178, -73.944730538)
('06-13', '2018', '06', '13', 'PETIT LARCENY', 40.832941761, -73.935432593)
('09-20', '2018', '09', '20', 'THEFT-FRAUD', 40.750657819, -73.98295161)
('10-17', '2018', '10', '17', 'GRAND LARCENY', 40.7887212430001, -73.939996774)
('11-28', '2018', '11', '28', 'PETIT LARCENY', 40.802336853, -73.949357635)
('01-03', '2018', '01', '03', 'GRAND LARCENY', 40.8006544360001, -73.956315447)
('04-12', '2018', '04', '12', 'THEFT-FRAUD', 40.8040460070001, -73.936620103)
('02-05', '2018', '02', '05', 'PETIT LARCENY', 40.833450977, -73.943407506)
('03-04', '2018', '03', '04', 'GRAND LARCENY', 40.711334838, -74.0054733649999)
('03-16', '2018', '03', '16', 'CRIMINAL MISCHIEF & RELATED OF', 40.807780622, -73.945484727)
('03-19', '2018', '03', '19', 'THEFT-FRAUD', 40.7970885840001, -73.9427485799999)
('05-08', '2018', '05', '08', 'RAPE', 40.800694331, -73.941109286)
('11-13', '2018', '11', '13', 'RAPE', 40.726554019, -73.987828427)
('12-09', '2018', '12', '09', 'OFF. AGNST PUB ORD SENSBLTY &', 40.7613359790001, -73.974112151)
('01-30', '2018', '01', '30', 'OFF. AGNST PUB ORD SENSBLTY &', 40.757346324, -73.9801813679999)
('05-03', '2018', '05', '03', 'FRAUDS', 40.8040460070001, -73.936620103)
('08-01', '2018', '08', '01', 'GRAND LARCENY', 40.756978196, -73.9783406129999)
('02-23', '2018', '02', '23', 'GRAND LARCENY', 40.763151029, -73.966472956)
('12-18', '2018', '12', '18', 'OFF. AGNST PUB ORD SENSBLTY &', 40.803555901, -73.9652317279999)
('12-18', '2018', '12', '18', 'HARRASSMENT 2', 40.7921665900001, -73.9698964409999)
('04-18', '2018', '04', '18', 'PROSTITUTION & RELATED OFFENSES', 40.753938938, -73.994843655)
('10-03', '2018', '10', '03', 'OFF. AGNST PUB ORD SENSBLTY &', 40.798483162, -73.9491474709999)
('03-16', '2018', '03', '16', 'CRIMINAL MISCHIEF & RELATED OF', 40.807780622, -73.945484727)
('03-20', '2018', '03', '20', 'SEX CRIMES', 40.8514877740001, -73.9354579669999)
('09-20', '2018', '09', '20', 'GRAND LARCENY', 40.757346324, -73.9801813679999)
('09-22', '2018', '09', '22', 'SEX CRIMES', 40.734226128, -74.005406689)
('03-29', '2018', '03', '29', 'GRAND LARCENY', 40.7385602210001, -73.999683896)
('03-11', '2018', '03', '11', 'GRAND LARCENY', 40.868151998, -73.9238321879999)
('10-09', '2018', '10', '09', 'HARRASSMENT 2', 40.762272884, -73.958567881)
('01-11', '2018', '01', '11', 'CRIMINAL MISCHIEF & RELATED OF', 40.717188305, -73.9831044649999)
('04-12', '2018', '04', '12', 'GRAND LARCENY', 40.792531066, -73.967772735)
('12-21', '2018', '12', '21', 'SEX CRIMES', 40.796571143, -73.967185687)
('05-04', '2018', '05', '04', 'OFF. AGNST PUB ORD SENSBLTY &', 40.746161946, -73.98312599)
('10-08', '2018', '10', '08', 'PETIT LARCENY', 40.837338537, -73.940050503)